export type ShapeId =
  | "sphere"
  | "box"
  | "cylinder"
  | "cone"
  | "torus"
  | "torusKnot"
  | "plane"
  | "ring"
  | "capsule"
  | "tetrahedron"
  | "octahedron"
  | "icosahedron"
  | "dodecahedron"
  | "circle";

export type ShapeCategory = "basic" | "prism" | "platonic" | "advanced";

export interface ParamDef {
  key: string;
  label: string;
  min: number;
  max: number;
  step: number;
  unit?: string;
  integer?: boolean;
}

export interface ComputedMetric {
  label: string;
  unit: string;
  compute: (p: Record<string, number>) => number | null;
}

export interface ShapeDef {
  id: ShapeId;
  name: string;
  description: string;
  category: ShapeCategory;
  params: ParamDef[];
  defaults: Record<string, number>;
  metrics: ComputedMetric[];
}

const PI = Math.PI;

export const SHAPE_CATEGORIES: Record<ShapeCategory, string> = {
  basic: "Basic Solids",
  prism: "Prisms & Surfaces",
  platonic: "Platonic Solids",
  advanced: "Advanced",
};

export const GEOMETRY_SHAPES: ShapeDef[] = [
  {
    id: "sphere",
    name: "Sphere",
    description: "All points equidistant from the center.",
    category: "basic",
    defaults: { radius: 1.2, widthSegments: 32, heightSegments: 24 },
    params: [
      { key: "radius", label: "Radius", min: 0.2, max: 3, step: 0.05, unit: "u" },
      { key: "widthSegments", label: "Width segments", min: 8, max: 64, step: 1, integer: true },
      { key: "heightSegments", label: "Height segments", min: 6, max: 48, step: 1, integer: true },
    ],
    metrics: [
      { label: "Diameter", unit: "u", compute: (p) => 2 * p.radius },
      { label: "Volume", unit: "u³", compute: (p) => (4 / 3) * PI * p.radius ** 3 },
      { label: "Surface area", unit: "u²", compute: (p) => 4 * PI * p.radius ** 2 },
    ],
  },
  {
    id: "box",
    name: "Box (Cuboid)",
    description: "A rectangular prism with width, height, and depth.",
    category: "basic",
    defaults: { width: 2, height: 1.5, depth: 1.2 },
    params: [
      { key: "width", label: "Width", min: 0.2, max: 4, step: 0.05, unit: "u" },
      { key: "height", label: "Height", min: 0.2, max: 4, step: 0.05, unit: "u" },
      { key: "depth", label: "Depth", min: 0.2, max: 4, step: 0.05, unit: "u" },
    ],
    metrics: [
      { label: "Volume", unit: "u³", compute: (p) => p.width * p.height * p.depth },
      {
        label: "Surface area",
        unit: "u²",
        compute: (p) => 2 * (p.width * p.height + p.height * p.depth + p.width * p.depth),
      },
    ],
  },
  {
    id: "cylinder",
    name: "Cylinder",
    description: "Circular prism — can taper with different top and bottom radii.",
    category: "basic",
    defaults: { radiusTop: 1, radiusBottom: 1, height: 2.2, radialSegments: 32 },
    params: [
      { key: "radiusTop", label: "Top radius", min: 0.1, max: 3, step: 0.05, unit: "u" },
      { key: "radiusBottom", label: "Bottom radius", min: 0.1, max: 3, step: 0.05, unit: "u" },
      { key: "height", label: "Height", min: 0.2, max: 5, step: 0.05, unit: "u" },
      { key: "radialSegments", label: "Radial segments", min: 8, max: 64, step: 1, integer: true },
    ],
    metrics: [
      { label: "Top diameter", unit: "u", compute: (p) => 2 * p.radiusTop },
      { label: "Bottom diameter", unit: "u", compute: (p) => 2 * p.radiusBottom },
      {
        label: "Volume",
        unit: "u³",
        compute: (p) => (PI * p.height * (p.radiusTop ** 2 + p.radiusTop * p.radiusBottom + p.radiusBottom ** 2)) / 3,
      },
    ],
  },
  {
    id: "cone",
    name: "Cone",
    description: "Tapers from a circular base to a single apex point.",
    category: "basic",
    defaults: { radius: 1.2, height: 2.4, radialSegments: 32 },
    params: [
      { key: "radius", label: "Base radius", min: 0.1, max: 3, step: 0.05, unit: "u" },
      { key: "height", label: "Height", min: 0.2, max: 5, step: 0.05, unit: "u" },
      { key: "radialSegments", label: "Radial segments", min: 8, max: 64, step: 1, integer: true },
    ],
    metrics: [
      { label: "Base diameter", unit: "u", compute: (p) => 2 * p.radius },
      { label: "Volume", unit: "u³", compute: (p) => (1 / 3) * PI * p.radius ** 2 * p.height },
      {
        label: "Slant height",
        unit: "u",
        compute: (p) => Math.sqrt(p.radius ** 2 + p.height ** 2),
      },
    ],
  },
  {
    id: "torus",
    name: "Torus (Donut)",
    description: "A ring-shaped surface generated by revolving a circle.",
    category: "advanced",
    defaults: { radius: 1.2, tube: 0.4, radialSegments: 16, tubularSegments: 48 },
    params: [
      { key: "radius", label: "Major radius", min: 0.3, max: 3, step: 0.05, unit: "u" },
      { key: "tube", label: "Tube radius", min: 0.05, max: 1.2, step: 0.05, unit: "u" },
      { key: "radialSegments", label: "Tube segments", min: 6, max: 32, step: 1, integer: true },
      { key: "tubularSegments", label: "Ring segments", min: 16, max: 96, step: 1, integer: true },
    ],
    metrics: [
      { label: "Outer diameter", unit: "u", compute: (p) => 2 * (p.radius + p.tube) },
      { label: "Inner diameter", unit: "u", compute: (p) => 2 * Math.max(0, p.radius - p.tube) },
      { label: "Volume", unit: "u³", compute: (p) => 2 * PI ** 2 * p.radius * p.tube ** 2 },
    ],
  },
  {
    id: "torusKnot",
    name: "Torus Knot",
    description: "A knot curve wrapped around a torus (p and q windings).",
    category: "advanced",
    defaults: { radius: 1, tube: 0.35, p: 2, q: 3, tubularSegments: 128, radialSegments: 16 },
    params: [
      { key: "radius", label: "Radius", min: 0.3, max: 2.5, step: 0.05, unit: "u" },
      { key: "tube", label: "Tube radius", min: 0.05, max: 0.8, step: 0.05, unit: "u" },
      { key: "p", label: "P windings", min: 1, max: 8, step: 1, integer: true },
      { key: "q", label: "Q windings", min: 1, max: 8, step: 1, integer: true },
      { key: "tubularSegments", label: "Path segments", min: 32, max: 256, step: 1, integer: true },
      { key: "radialSegments", label: "Tube segments", min: 6, max: 32, step: 1, integer: true },
    ],
    metrics: [],
  },
  {
    id: "plane",
    name: "Plane",
    description: "Flat rectangular surface in 3D space.",
    category: "prism",
    defaults: { width: 3, height: 2, widthSegments: 1, heightSegments: 1 },
    params: [
      { key: "width", label: "Width", min: 0.5, max: 6, step: 0.1, unit: "u" },
      { key: "height", label: "Height", min: 0.5, max: 6, step: 0.1, unit: "u" },
      { key: "widthSegments", label: "Width segments", min: 1, max: 32, step: 1, integer: true },
      { key: "heightSegments", label: "Height segments", min: 1, max: 32, step: 1, integer: true },
    ],
    metrics: [
      { label: "Area", unit: "u²", compute: (p) => p.width * p.height },
    ],
  },
  {
    id: "ring",
    name: "Ring",
    description: "Flat annulus — a disc with a hole in the center.",
    category: "prism",
    defaults: { innerRadius: 0.5, outerRadius: 1.2, thetaSegments: 32 },
    params: [
      { key: "innerRadius", label: "Inner radius", min: 0.05, max: 2.5, step: 0.05, unit: "u" },
      { key: "outerRadius", label: "Outer radius", min: 0.1, max: 3, step: 0.05, unit: "u" },
      { key: "thetaSegments", label: "Segments", min: 8, max: 64, step: 1, integer: true },
    ],
    metrics: [
      { label: "Inner diameter", unit: "u", compute: (p) => 2 * p.innerRadius },
      { label: "Outer diameter", unit: "u", compute: (p) => 2 * p.outerRadius },
      {
        label: "Area",
        unit: "u²",
        compute: (p) => PI * (p.outerRadius ** 2 - p.innerRadius ** 2),
      },
    ],
  },
  {
    id: "capsule",
    name: "Capsule",
    description: "Cylinder with hemispherical caps on both ends.",
    category: "advanced",
    defaults: { radius: 0.6, length: 1.8, capSegments: 12, radialSegments: 24 },
    params: [
      { key: "radius", label: "Radius", min: 0.1, max: 2, step: 0.05, unit: "u" },
      { key: "length", label: "Cylinder length", min: 0.2, max: 4, step: 0.05, unit: "u" },
      { key: "capSegments", label: "Cap segments", min: 4, max: 24, step: 1, integer: true },
      { key: "radialSegments", label: "Radial segments", min: 8, max: 48, step: 1, integer: true },
    ],
    metrics: [
      { label: "Diameter", unit: "u", compute: (p) => 2 * p.radius },
      { label: "Total height", unit: "u", compute: (p) => p.length + 2 * p.radius },
    ],
  },
  {
    id: "circle",
    name: "Circle",
    description: "A flat circular outline (1-sided ring).",
    category: "prism",
    defaults: { radius: 1.2, segments: 48 },
    params: [
      { key: "radius", label: "Radius", min: 0.1, max: 3, step: 0.05, unit: "u" },
      { key: "segments", label: "Segments", min: 8, max: 128, step: 1, integer: true },
    ],
    metrics: [
      { label: "Diameter", unit: "u", compute: (p) => 2 * p.radius },
      { label: "Circumference", unit: "u", compute: (p) => 2 * PI * p.radius },
    ],
  },
  {
    id: "tetrahedron",
    name: "Tetrahedron",
    description: "4-faced platonic solid — triangular pyramid.",
    category: "platonic",
    defaults: { radius: 1.4 },
    params: [{ key: "radius", label: "Radius", min: 0.3, max: 3, step: 0.05, unit: "u" }],
    metrics: [
      { label: "Diameter", unit: "u", compute: (p) => 2 * p.radius },
      { label: "Volume", unit: "u³", compute: (p) => (8 / (9 * Math.sqrt(3))) * p.radius ** 3 },
    ],
  },
  {
    id: "octahedron",
    name: "Octahedron",
    description: "8-faced platonic solid — two square pyramids joined.",
    category: "platonic",
    defaults: { radius: 1.4 },
    params: [{ key: "radius", label: "Radius", min: 0.3, max: 3, step: 0.05, unit: "u" }],
    metrics: [
      { label: "Diameter", unit: "u", compute: (p) => 2 * p.radius },
    ],
  },
  {
    id: "icosahedron",
    name: "Icosahedron",
    description: "20-faced platonic solid — made of equilateral triangles.",
    category: "platonic",
    defaults: { radius: 1.4 },
    params: [{ key: "radius", label: "Radius", min: 0.3, max: 3, step: 0.05, unit: "u" }],
    metrics: [
      { label: "Diameter", unit: "u", compute: (p) => 2 * p.radius },
    ],
  },
  {
    id: "dodecahedron",
    name: "Dodecahedron",
    description: "12-faced platonic solid — each face is a regular pentagon.",
    category: "platonic",
    defaults: { radius: 1.4 },
    params: [{ key: "radius", label: "Radius", min: 0.3, max: 3, step: 0.05, unit: "u" }],
    metrics: [
      { label: "Diameter", unit: "u", compute: (p) => 2 * p.radius },
    ],
  },
];

export function getShapeById(id: ShapeId): ShapeDef | undefined {
  return GEOMETRY_SHAPES.find((s) => s.id === id);
}

export function getDefaultParams(shape: ShapeDef): Record<string, number> {
  return { ...shape.defaults };
}

export function formatMetric(value: number | null, decimals = 2): string {
  if (value === null || Number.isNaN(value)) return "—";
  if (Math.abs(value) >= 1000) return value.toExponential(2);
  return value.toFixed(decimals);
}
